#ifndef SECRET_H
#define SECRET_H

#define XSTR(x) #x
#define STR(x) XSTR(x)
#define LIST(x) { x }

#define WIFI_SSID STR(SSID)
#define WIFI_PASS STR(PASS)

#define NTP_SERVERS LIST(SNTP_SERVERS)
#define NTP_SERVERS_SIZE SNTP_SERVERS_LEN

#define RGBLED RGBLED_PIN 
#define TIME_SYNC_INTERVAL SNTP_UPDATE_INTERVAL
#define TIME_SYNC_FAIL_INTERVAL SNTP_UPDATE_FAILURES_INTERVAL
#define TIME_SYNC_FAILURE_THRESHOLD SNTP_UPDATE_MAX_RETRIES

#define MQTT_SERVER STR(MQTT_SERVER_IP)
#define MQTT_PORT MQTT_SERVER_PORT
#define MQTT_USER STR(MQTT_USERNAME)
#define MQTT_PASS STR(MQTT_PASSWORD)

#define OTA_USER STR(OTA_USERNAME)
#define OTA_PASS STR(OTA_PASSWORD)

#endif